/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBalanceRouteImport } from './routes/_authenticated/balance'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedFollowingRouteImport } from './routes/_authenticated/following'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMarketsRouteImport } from './routes/_authenticated/markets'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedMarketMarketIdRouteImport } from './routes/_authenticated/market.$marketId'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBalanceRoute = AuthenticatedBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowingRoute = AuthenticatedFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketsRoute = AuthenticatedMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketMarketIdRoute =
  AuthenticatedMarketMarketIdRouteImport.update({
    id: '/market/$marketId',
    path: '/market/$marketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/following': typeof AuthenticatedFollowingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/market/$marketId': typeof AuthenticatedMarketMarketIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/following': typeof AuthenticatedFollowingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/market/$marketId': typeof AuthenticatedMarketMarketIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/balance': typeof AuthenticatedBalanceRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/following': typeof AuthenticatedFollowingRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/markets': typeof AuthenticatedMarketsRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/_authenticated/market/$marketId': typeof AuthenticatedMarketMarketIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/balance'
    | '/discover'
    | '/following'
    | '/home'
    | '/markets'
    | '/portfolio'
    | '/profile'
    | '/watchlist'
    | '/market/$marketId'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/balance'
    | '/discover'
    | '/following'
    | '/home'
    | '/markets'
    | '/portfolio'
    | '/profile'
    | '/watchlist'
    | '/market/$marketId'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/balance'
    | '/_authenticated/discover'
    | '/_authenticated/following'
    | '/_authenticated/home'
    | '/_authenticated/markets'
    | '/_authenticated/portfolio'
    | '/_authenticated/profile'
    | '/_authenticated/watchlist'
    | '/_authenticated/market/$marketId'
    | '/_authenticated/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/balance': {
      id: '/_authenticated/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthenticatedBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/following': {
      id: '/_authenticated/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof AuthenticatedFollowingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/markets': {
      id: '/_authenticated/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AuthenticatedMarketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/$marketId': {
      id: '/_authenticated/market/$marketId'
      path: '/market/$marketId'
      fullPath: '/market/$marketId'
      preLoaderRoute: typeof AuthenticatedMarketMarketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBalanceRoute: typeof AuthenticatedBalanceRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFollowingRoute: typeof AuthenticatedFollowingRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMarketsRoute: typeof AuthenticatedMarketsRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedMarketMarketIdRoute: typeof AuthenticatedMarketMarketIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBalanceRoute: AuthenticatedBalanceRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFollowingRoute: AuthenticatedFollowingRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMarketsRoute: AuthenticatedMarketsRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedMarketMarketIdRoute: AuthenticatedMarketMarketIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
